sudo: false
language: node_js
node_js:
  - 0.12
  - iojs
branches:
  only:
    - master
script: npm run-script test-travis
after_success: npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls